
services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception_network
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception_network
    depends_on:
      - mariadb
    restart: on-failure

volumes:
  mariadb_vol:
    name: mariadb_vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/feden-pe/data/mariadb_vol
  wordpress_vol:
    name: wordpress_vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/feden-pe/data/wordpress_vol

networks:
  inception_network:
    name: inception_network
