
services:
  mariadb:
    image: mariadb
    restart: always
    env_file:
      - .env
    # volumes:
      # - .data:/var/lib/mysql
      #


  networks:
    inception_network:
      name: inception_network
